apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: sm-prod-cred
    namespace: prod
  type: Opaque
  data:
    clouds.yaml: Y2xvdWRzOgogIG9ucHJlbToKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwczovL2FwcC5pbmZyYS5wcm9kLm9wZW5zaGlmdC5sZWFrdGsub3JnOjIwMjAvdjMKICAgICAgdXNlcm5hbWU6ICJwcm9kLWFwcCIKICAgICAgcHJvamVjdF9pZDogMmQwMTMyZjVhYTkwZWEwNDRhOThlOGVkMjUzNmNhM2YKICAgICAgcHJvamVjdF9uYW1lOiAicHJvZC1kZXBsb3ltZW50IgogICAgICB1c2VyX2RvbWFpbl9uYW1lOiAibGVha3RrLm9yZyIKICAgICAgcGFzc3dvcmQ6ICJ0MnpPOjI1QlktU2t2bHl4OHJadHhteVlYNGJTamlpYyIKICAgIHJlZ2lvbl9uYW1lOiAicmVnaW9uT25lIgogICAgaW50ZXJmYWNlOiAicHVibGljIgogICAgaWRlbnRpdHlfYXBpX3ZlcnNpb246IDMKICByb3NhOgogICAgYXV0aDoKICAgICAgYXV0aF91cmw6IGh0dHBzOi8vYXBwLmluZnJhLnByb2Qub3BlbnNoaWZ0LmxlYWt0ay5vcmc6MjAyMC92MwogICAgICB1c2VybmFtZTogInByb2QtYXBwIgogICAgICBwcm9qZWN0X2lkOiAyZDAxMzJmNWFhOTBlYTA0NGE5OGU4ZWQyNTM2Y2EzZgogICAgICBwcm9qZWN0X25hbWU6ICJwcm9kLWRlcGxveW1lbnQiCiAgICAgIHVzZXJfZG9tYWluX25hbWU6ICJsZWFrdGsub3JnIgogICAgICBwYXNzd29yZDogInQyek86MjVCWS1Ta3ZseXg4clp0eG15WVg0YlNqaWljIgogICAgcmVnaW9uX25hbWU6ICJyZWdpb25PbmUiCiAgICBpbnRlcmZhY2U6ICJwdWJsaWMiCiAgICBpZGVudGl0eV9hcGlfdmVyc2lvbjogMwo=
    cloud: b25wcmVt
