name: Run load tests

on:
  schedule:
    - cron: "15 * * * *"

jobs:
  load_test:
    strategy:
      matrix:
        cluster:
          - label: preprod-ltk01
            repo: https://github.com/leaktk/fake-leaks.git
            member_cluster_secret: MEMBER_CLUSTER_PREPROD_LEAK_TK01
            ocp_prometheus_token_secret: OCP_PROMETHEUS_TOKEN_PREPROD_LEAK_TK01
            users_secret: USERS_PREPROD_LEAK_TK01
          - label: prod-ltk01
            repo: https://github.com/leaktk/fake-leaks.git
            member_cluster_secret: MEMBER_CLUSTER_PROD_LEAK_TK01
            ocp_prometheus_token_secret: OCP_PROMETHEUS_TOKEN_PROD_LEAK_TK01
            users_secret: USERS_PROD_LEAK_TK01
